name: Create Extension File
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: ./flixel-atlas-export
        filename: 'flixel-atlas-export.aseprite-extension'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "flixel-atlas-export.aseprite-extension"
        token: ${{ secrets.GITHUB_TOKEN }}