name: Build Release
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@master
    - name: Set Plugin Version
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "BUILD_TAG"
        replace: "${{ GITHUB_REF_NAME }}"
        regex: false
        include: "**package.json"
    - name: Create Extension Package
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        directory: ./flixel-atlas-export
        filename: 'flixel-atlas-export.aseprite-extension'
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        bodyFile: "README.md"
        artifacts: "./flixel-atlas-export/flixel-atlas-export.aseprite-extension"
        token: ${{ secrets.GITHUB_TOKEN }}